CREATE DATABASE loja;

USE loja;

CREATE TABLE paises(
	id_pais INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(191) NOT NULL,
    ddi INT
);

CREATE TABLE estados(
	id_estado INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(191) NOT NULL,
    sigla CHAR(2),
	pais_id INT UNSIGNED NOT NULL
);

CREATE TABLE cidades(
	id_cidade INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(191) NOT NULL,
    estado_id INT UNSIGNED NOT NULL
);

CREATE TABLE clientes(
	id_cliente INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(191) NOT NULL,
	documento VARCHAR(191) NOT NULL,
	data_nascimento DATE,
	sexo CHAR(1),
	telefone VARCHAR(191),
	email VARCHAR(191),
	endereco_1 VARCHAR(191) NOT NULL,
	endereco_2 VARCHAR(191),
	codigo_postal INT UNSIGNED,
	cidade_id INT UNSIGNED NOT NULL
);

SHOW TABLES;

SHOW DATABASES;